export const SIGN_IN_WITH_APPLE = 'SIGN_IN_WITH_APPLE';

export const REQUEST_APPLE_CONFIG = 'REQUEST_APPLE_CONFIG';
export const REQUEST_APPLE_CONFIG_SUCCESS = 'REQUEST_APPLE_CONFIG_SUCCESS';
export const REQUEST_APPLE_CONFIG_ERROR = 'REQUEST_APPLE_CONFIG_ERROR';
